#!/bin/bash

# The Databses that need to be created
# DBS="acoustic basemap bioregions bio bio_atlas chat-call cli_map corax2005 nzoa nzoi nzpolitical os2020_oceans test test_mafbnz trawl"

# Imports the constants including WMS
source ~/.bash_profile

DBS=`psql -l -At -h $WMS | grep -v "=" | cut -f1 -d "|"`

echo $DBS

# Create each database in the list of databases
for DB in $DBS; do
	dropdb $DB
        echo "Creating database ${DB}."
        createdb $DB
	echo "Add Postgis extension"
	psql -d $DB -tAc "create extension postgis;" 	
done

echo "Finished"
