#!/bin/bash

# Author: Jesse Wood 
# Date: 2020-10-05

# Imports the constants including WMS
source ~/.bash_profile

# The databases that need to be created
# This pipeline gets the list of databases from the original server
# This list excludes that datbases like `postgres=...`
DBS=`psql -l -At -h $WMS | grep -v "=" | cut -f1 -d "|"`

echo $DBS

# Create each database in the list of databases
for DB in $DBS; do
	dropdb $DB
        echo "Creating database ${DB}."
        createdb $DB
	echo "Add Postgis extension"
	psql -d $DB -tAc "create extension postgis;" 	
done

echo "Finished"
